(() => {
const course={
icon:"📐",
description:"মূল ধারণা থেকে guided practice পর্যন্ত একটি সুসংগঠিত গণিত learning pathway।",
topics:{
"Arithmetic & Number Sense":["Arithmetic নির্ভরযোগ্য number sense, operation, estimation এবং mathematical notation গড়ে তোলে।","Sign, unit, order of operations এবং ফলাফলের reasonableness যাচাই করুন।","Example: 240-এর 25% = 0.25×240 = 60।"],
"Algebra & Equations":["Algebra symbol, expression, equation এবং inequality দিয়ে relationship প্রকাশ করে।","দুই পাশে equality বজায় রেখে simplify করুন এবং restriction যাচাই করুন।","Example: 3x+2=14 হলে x=4; substitution দিয়ে ফল যাচাই করা যায়।"],
"Geometry & Mensuration":["Geometry shape, angle, distance, area, volume এবং spatial relationship নিয়ে কাজ করে।","Figure আঁকুন, known quantity label করুন, theorem নির্বাচন করুন এবং unit consistent রাখুন।","Example: length 8 ও width 5 হলে rectangle-এর area 40 square units।"],
"Trigonometry":["Trigonometry angle, ratio, function এবং periodic relationship-এর মধ্যে সংযোগ তৈরি করে।","Triangle বা identity শনাক্ত করুন এবং degree/radian convention যাচাই করুন।","Example: sin²θ+cos²θ=1 একটি identity।"],
"Functions & Graphs":["Function প্রতিটি allowed input-কে একটি নির্দিষ্ট output-এর সঙ্গে map করে।","Domain, key feature, composition এবং inverse-এর condition চিহ্নিত করুন।","Example: f(x)=2x+1 হলে f(3)=7।"],
"Coordinate Geometry & Vectors":["Coordinate geometry ও vectors geometric relationship-কে algebraic representation-এ প্রকাশ করে।","Coordinate, direction, magnitude এবং dimension স্পষ্ট রাখুন।","Example: (0,0) ও (3,4)-এর distance = 5 units।"],
"Calculus":["Calculus change, accumulation, limit এবং approximation নিয়ে কাজ করে।","Derivative ও integral-এর পার্থক্য, condition এবং context-এর interpretation স্পষ্ট করুন।","Example: f(x)=x⁵ হলে f′(x)=5x⁴।"],
"Linear Algebra":["Linear algebra vector, matrix, linear transformation এবং system of equations নিয়ে কাজ করে।","Matrix dimension যাচাই করুন এবং solution-এর algebraic ও geometric অর্থ বিবেচনা করুন।","Example: Ax=b একটি linear system।"],
"Probability & Combinatorics":["Probability uncertainty পরিমাপ করে এবং combinatorics structured possibility count করে।","প্রথমে sample space ও event সংজ্ঞায়িত করুন।","Example: P(A|B)=P(A∩B)/P(B), যেখানে P(B)>0।"],
"Statistics & Data Reasoning":["Statistics data-কে summary, estimate, model এবং evidence-এ রূপান্তর করে।","Descriptive summary ও inference আলাদা রাখুন এবং sampling, variability ও assumptions পরীক্ষা করুন।","Example: mean একা skewness বা outlier দেখায় না।"],
"Discrete Mathematics & Logic":["Discrete mathematics finite/countable structure, algorithm, relation এবং logical reasoning নিয়ে কাজ করে।","Statement-কে precise proposition-এ রূপান্তর করুন এবং edge case পরীক্ষা করুন।","Example: contradiction proof-এ claim-এর negation ধরে inconsistency দেখানো হয়।"],
"Real & Complex Analysis":["Analysis limit, continuity, convergence, differentiation ও integration-কে rigorous definition ও proof-এর মাধ্যমে formalize করে।","Hypothesis স্পষ্টভাবে লিখুন এবং intuition ও proof আলাদা রাখুন।","Example: sequence convergence epsilon-based condition দিয়ে সংজ্ঞায়িত হয়।"],
"Abstract Algebra & Number Theory":["Abstract algebra group, ring, field এবং number theory integer ও arithmetic structure নিয়ে কাজ করে।","Definition থেকে শুরু করুন এবং structural condition যাচাই করুন।","Example: integers modulo n একটি ring গঠন করে।"],
"Differential Equations & Modelling":["Differential equation rate of change-এর relationship প্রকাশ করে এবং dynamic system model করতে ব্যবহৃত হয়।","Initial/boundary condition লিখুন এবং exact ও numerical solution আলাদা করুন।","Example: y′=ky-এর solution y=Ce^{kx}।"],
"Numerical Methods & Optimization":["Numerical mathematics approximate solution দেয় এবং optimization constraint-এর মধ্যে objective minimize/maximize করে।","Convergence, stability, tolerance এবং computed solution পরীক্ষা করুন।","Example: gradient descent objective কমানোর দিকে parameter update করে।"],
"Financial & Risk Mathematics":["Financial mathematics discounting, compounding, probability এবং stochastic ideas দিয়ে valuation ও risk বিশ্লেষণ করে।","Cash-flow timing, rate convention, compounding এবং model assumption স্পষ্ট করুন।","Example: present value future cash flow discount করে।"],
"AI & Machine Learning Mathematics":["AI/ML-এ linear algebra, probability, calculus, statistics এবং optimization গুরুত্বপূর্ণ।","Mathematical objective, implementation এবং evaluation assumptions আলাদা করে যাচাই করুন।","Example: gradient descent objective function কমানোর দিকে parameter update করে।"],
"Cryptography Mathematics":["Modern cryptography information protection-এর জন্য number theory, algebra, probability ও computational complexity ব্যবহার করে।","Mathematical security assumption, implementation এবং key management আলাদা করে বুঝুন।","Example: modular arithmetic ও finite-field operations cryptographic construction-এর ভিত্তি।"]
};
const CASE_STUDIES=[
{level:"School → Intermediate",title:"Community Hall Measurement",scenario:"একজন student একটি rectangular hall, triangular garden এবং circular water feature-এর measurement নিয়ে material estimate প্রস্তুত করে।",tasks:["সঠিক perimeter/area formula নির্বাচন করুন।","প্রতিটি ধাপে unit দেখান।","Geometry প্রয়োজন হলে Pythagoras বা trigonometry ব্যবহার করুন।"],lesson:"Formula selection নিজেই mathematical reasoning-এর অংশ; diagram, units এবং assumptions স্পষ্ট থাকা প্রয়োজন।"},
{level:"Intermediate",title:"Loan and Savings Model",scenario:"পাঁচ বছরের জন্য ভিন্ন rate ও compounding period-যুক্ত দুটি savings plan তুলনা করা হচ্ছে।",tasks:["Rate এবং period consistentভাবে রূপান্তর করুন।","Future value এবং effective return হিসাব করুন।","Nominal rate একা কেন যথেষ্ট নয় তা ব্যাখ্যা করুন।"],lesson:"Time, rate এবং compounding-এর assumptions consistent রাখতে হবে।"}
];
const q=s=>document.querySelector(s),qs=s=>[...document.querySelectorAll(s)];
const subject="Mathematics";
q("#courseIcon").textContent=course.icon;q("#courseTitle").textContent=subject;q("#courseDescription").textContent=course.description;
const path=q(".learning-path");if(path){path.innerHTML='<div class="learning-path-grid"><div class="learning-step"><b>01 · LEARN</b><strong>ধারণা গড়ুন</strong><span>Guided lesson পড়ে মূল ধারণাটি চিহ্নিত করুন।</span></div><div class="learning-step"><b>02 · PRACTICE</b><strong>প্রয়োগ করুন</strong><span>Worked example ব্যবহার করে topic practice করুন।</span></div><div class="learning-step"><b>03 · SELF-CHECK</b><strong>নিজেকে যাচাই করুন</strong><span>Quick practice সম্পন্ন করে feedback দেখুন।</span></div><div class="learning-step"><b>04 · EVIDENCE</b><strong>Learning record রাখুন</strong><span>Completion mark করে এই device-এ study record রাখুন।</span></div></div>'}
const keys=Object.keys(course.topics),storage="studentCourse:"+subject,saved=JSON.parse(localStorage.getItem(storage)||"{}");
const syllabus=q("#syllabus");keys.forEach((t,i)=>{const b=document.createElement("button");b.className="topic-link";b.textContent=(i+1)+". "+t;b.onclick=()=>loadTopic(t);syllabus.appendChild(b)});
q("#topicCount").textContent=keys.length+" topics";q("#courseProgress").textContent=Object.keys(saved).length+" completed";
const cards=q("#courseCards");keys.forEach(t=>{const d=course.topics[t],a=document.createElement("article");a.className="course-card";a.innerHTML='<h3>'+t+'</h3><p>'+d[0]+'</p><button class="btn primary" type="button">Study শুরু করুন →</button>';a.querySelector("button").onclick=()=>loadTopic(t);cards.appendChild(a)});
function loadTopic(t){const d=course.topics[t];qs(".topic-link").forEach(b=>b.classList.toggle("active",b.textContent.endsWith(t)));q("#lessonTitle").textContent=t;q("#concept").textContent=d[0];q("#method").textContent=d[1];q("#example").textContent=d[2];q("#lessonStatus").textContent=saved[t]?"এই device-এ সম্পন্ন":"এখনও সম্পন্ন হয়নি";q("#lesson").scrollIntoView({behavior:"smooth",block:"start"});q("#quiz").hidden=true}
q("#complete").onclick=()=>{const t=q("#lessonTitle").textContent;if(!course.topics[t])return;saved[t]=new Date().toISOString();localStorage.setItem(storage,JSON.stringify(saved));q("#lessonStatus").textContent="এই device-এ সম্পন্ন";q("#courseProgress").textContent=Object.keys(saved).length+" completed"};
q("#practice").onclick=()=>{const t=q("#lessonTitle").textContent,d=course.topics[t];q("#quizQuestion").textContent=t+"-এর সঙ্গে সবচেয়ে উপযুক্ত statement কোনটি?";const opts=[d[0],d[1],d[2],"এই topic সবসময় context বা verification ছাড়া প্রয়োগ করা উচিত।"];const shuffled=opts.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);const box=q("#quizOptions");box.innerHTML="";shuffled.forEach(o=>{const l=document.createElement("label");l.innerHTML='<input type="radio" name="courseq" value="'+encodeURIComponent(o)+'"> '+o;box.appendChild(l)});q("#quiz").hidden=false};
q("#checkQuiz").onclick=()=>{const t=q("#lessonTitle").textContent,d=course.topics[t],v=document.querySelector('input[name="courseq"]:checked');if(!v){q("#result").textContent="আগে একটি answer নির্বাচন করুন।";return}q("#result").textContent=decodeURIComponent(v.value)===d[0]?"সঠিক। Concept review করে পরের topic-এ যান।":"Lesson review করুন: প্রথম statement-টিই এই topic-এর মূল concept।"};
const host=q(".course-grid"),cases=CASE_STUDIES;
if(host&&!q("#case-studies")){const s=document.createElement("section");s.className="case-study-section";s.id="case-studies";s.innerHTML='<div class="case-study-head"><span class="case-study-kicker">CASE STUDY · APPLICATION</span><h2>Practical scenario থেকে শিখুন</h2><p>Concept → evidence → reasoning → conclusion-এর সংযোগ বুঝতে case ব্যবহার করুন। এগুলো educational scenario; professional approval বা real client record নয়।</p></div><div class="case-study-grid"></div>';const grid=s.querySelector(".case-study-grid");cases.forEach(x=>{const a=document.createElement("article");a.className="case-study-card";a.innerHTML='<span class="case-study-level">'+x.level+'</span><h3>'+x.title+'</h3><p><b>Scenario:</b> '+x.scenario+'</p><p><b>Student tasks:</b></p><ul>'+x.tasks.map(t=>'<li>'+t+'</li>').join("")+'</ul><div class="case-study-lesson"><b>Key lesson:</b> '+x.lesson+'</div>';grid.appendChild(a)});host.insertAdjacentElement("afterend",s)}
const actions=q(".course-hero-inner .lesson-meta");if(actions&&!q("#formulaLibraryLink")){const a=document.createElement("a");a.id="formulaLibraryLink";a.className="formula-library-cta";a.href="formulas-bn.html";a.textContent="Formula Library খুলুন →";actions.appendChild(a)}
const printBtn=document.createElement("button");printBtn.className="btn secondary";printBtn.type="button";printBtn.textContent="Print / Save as PDF";printBtn.onclick=()=>{const title=document.title;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||"—"};set("printTopic",q("#lessonTitle")?.textContent);set("printConcept",q("#concept")?.textContent);set("printMethod",q("#method")?.textContent);set("printExample",q("#example")?.textContent);document.title="RegTech Nexus AI — Mathematics — "+(q("#lessonTitle")?.textContent||"Study");window.print();setTimeout(()=>document.title=title,900)};q(".actions")?.appendChild(printBtn);
loadTopic(keys[0]);
})();